//go:build windows

package main

import (
    "crypto/rand"
    "encoding/hex"
    "fmt"
    "html"
    "io"
    "net"
    "net/http"
    "os"
    "os/exec"
    "path/filepath"
    "strconv"
    "strings"
    "sync"
    "time"
)

type PreviewBundle struct { P Preview; Source string }
type App struct { store *Store; previews map[string]PreviewBundle; mu sync.Mutex; server *http.Server }

const css = `
:root{--green:#0D4E3A;--gold:#B88B30;--ink:#17211d;--muted:#66736d;--line:#dfe6e2;--bg:#f5f7f6;--white:#fff;--danger:#8d2424;--warn:#8a5a00}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Segoe UI,Arial,sans-serif}.top{background:var(--green);color:#fff;padding:17px 28px;display:flex;align-items:center;justify-content:space-between}.brand{font-weight:750;letter-spacing:.3px;font-size:20px}.brand span{color:#e4c574}.nav a{color:#fff;text-decoration:none;margin-left:18px;font-size:14px}.wrap{max-width:1160px;margin:28px auto;padding:0 22px}.panel{background:#fff;border:1px solid var(--line);border-radius:14px;padding:22px;margin:0 0 18px;box-shadow:0 2px 9px rgba(0,0,0,.035)}h1{font-size:27px;margin:0 0 18px;color:var(--green)}h2{font-size:18px;margin:0 0 14px;color:var(--green)}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.metric{font-size:30px;font-weight:750;color:var(--green)}.muted{color:var(--muted);font-size:14px}.btn,button{display:inline-block;border:0;border-radius:9px;background:var(--green);color:#fff;padding:10px 15px;text-decoration:none;font-weight:650;cursor:pointer}.btn.alt{background:#fff;color:var(--green);border:1px solid var(--green)}.btn.gold{background:var(--gold)}input,select{width:100%;padding:10px 11px;border:1px solid #cfd8d3;border-radius:8px;background:#fff;font:inherit}label{display:block;font-weight:600;font-size:14px;margin-bottom:12px}.formgrid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.full{grid-column:1/-1}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:10px 9px;border-bottom:1px solid #e8ecea;vertical-align:top}th{color:var(--green);font-size:12px;text-transform:uppercase;letter-spacing:.35px}.ok{color:#136c49;font-weight:700}.warn{color:var(--warn);font-weight:700}.danger{color:var(--danger);font-weight:700}.flash{padding:12px 14px;background:#edf7f2;border-left:4px solid var(--green);margin-bottom:16px;border-radius:7px}.flash.bad{background:#fff0f0;border-color:var(--danger)}.actions{display:flex;gap:9px;flex-wrap:wrap}.tag{display:inline-block;padding:4px 8px;border-radius:999px;background:#edf2ef;font-size:12px}.right{text-align:right}@media(max-width:760px){.grid,.formgrid{grid-template-columns:1fr}.nav{display:none}.wrap{padding:0 12px}.panel{padding:16px}table{display:block;overflow:auto}}
`

func esc(s string) string { return html.EscapeString(s) }
func brMoney(c int64) string { v:=fmt.Sprintf("%.2f",float64(c)/100);parts:=strings.Split(v,".");a:=parts[0];for i:=len(a)-3;i>0;i-=3{a=a[:i]+"."+a[i:]};return "R$ "+a+","+parts[1] }
func page(title,body,msg string,bad bool) string { var f string;if msg!=""{cl:="flash";if bad{cl+=" bad"};f=`<div class="`+cl+`">`+esc(msg)+`</div>`};return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>`+esc(title)+` — GD Fiscal Saúde</title><style>`+css+`</style></head><body><div class="top"><div class="brand">GD <span>Fiscal Saúde</span></div><div class="nav"><a href="/">Início</a><a href="/professionals">Profissionais</a><a href="/import">Importar Excel</a><a href="/payments">Lançamentos</a><a href="/restrictions">Pendências</a><a href="/export">Exportar</a><a href="/exit">Sair</a></div></div><main class="wrap">`+f+body+`</main></body></html>` }
func redirectMsg(w http.ResponseWriter,r *http.Request,path,msg string,bad bool){sep:="?";if strings.Contains(path,"?"){sep="&"};http.Redirect(w,r,path+sep+"msg="+urlEncode(msg)+"&bad="+strconv.FormatBool(bad),http.StatusSeeOther)}
func urlEncode(s string)string{return strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(s,"%","%25")," ","%20"),"&","%26"),"?","%3F")}
func message(r *http.Request)(string,bool){return r.URL.Query().Get("msg"),r.URL.Query().Get("bad")=="true"}
func intForm(r *http.Request,key string)int64{v,_:=strconv.ParseInt(r.FormValue(key),10,64);return v}

func (a *App) routes()*http.ServeMux{m:=http.NewServeMux();m.HandleFunc("/",a.home);m.HandleFunc("/professionals",a.professionals);m.HandleFunc("/professionals/new",a.professionalNew);m.HandleFunc("/import",a.importPage);m.HandleFunc("/payments",a.payments);m.HandleFunc("/validate",a.validate);m.HandleFunc("/export",a.export);m.HandleFunc("/restrictions",a.restrictions);m.HandleFunc("/restrictions/resolve",a.resolveRestriction);m.HandleFunc("/exit",a.exit);m.HandleFunc("/health",func(w http.ResponseWriter,r *http.Request){w.Write([]byte("ok"))});return m}
func (a *App) home(w http.ResponseWriter,r *http.Request){if r.URL.Path!="/"{http.NotFound(w,r);return};pc,pay,rest,e:=a.store.Counts();if e!=nil{http.Error(w,e.Error(),500);return};body:=fmt.Sprintf(`<h1>Organização fiscal por profissional</h1><section class="grid"><div class="panel"><div class="metric">%d</div><div class="muted">profissionais ativos</div></div><div class="panel"><div class="metric">%d</div><div class="muted">lançamentos persistidos</div></div><div class="panel"><div class="metric">%d</div><div class="muted">pendências para correção</div></div></section><section class="panel"><h2>Fluxo operacional</h2><div class="actions"><a class="btn" href="/professionals">1. Cadastrar profissional</a><a class="btn" href="/import">2. Importar Excel</a><a class="btn" href="/payments">3. Validar lançamentos</a><a class="btn gold" href="/export">4. Exportar escrituração</a></div><p class="muted" style="margin-top:16px">Dados gravados localmente em SQLite. Nenhum dado fiscal é enviado para nuvem.</p></section>`,pc,pay,rest);msg,b:=message(r);io.WriteString(w,page("Início",body,msg,b))}
func (a *App) professionals(w http.ResponseWriter,r *http.Request){ps,e:=a.store.Professionals();if e!=nil{http.Error(w,e.Error(),500);return};var b strings.Builder;b.WriteString(`<div class="actions" style="justify-content:space-between"><h1>Profissionais</h1><a class="btn" href="/professionals/new">Adicionar profissional</a></div><section class="panel"><table><thead><tr><th>Nome</th><th>CPF</th><th>Registro</th><th>Ocupação</th></tr></thead><tbody>`);for _,p:=range ps{b.WriteString(`<tr><td><strong>`+esc(p.Name)+`</strong></td><td>`+esc(formatCPF(p.CPF))+`</td><td>`+esc(p.Registry)+`</td><td>Psicólogo · 255</td></tr>`)};b.WriteString(`</tbody></table></section>`);msg,bad:=message(r);io.WriteString(w,page("Profissionais",b.String(),msg,bad))}
func (a *App) professionalNew(w http.ResponseWriter,r *http.Request){if r.Method==http.MethodPost{name:=r.FormValue("name");cpf:=r.FormValue("cpf");reg:=r.FormValue("registry");if _,e:=a.store.AddProfessional(name,cpf,reg);e!=nil{redirectMsg(w,r,"/professionals/new",e.Error(),true);return};redirectMsg(w,r,"/professionals","Profissional cadastrado e salvo.",false);return};body:=`<h1>Adicionar profissional</h1><form method="post" class="panel formgrid"><label>Nome completo<input name="name" required></label><label>CPF<input name="cpf" required inputmode="numeric"></label><label>Registro profissional<input name="registry" placeholder="CRP / CRM / CRO ..."></label><label>Profissão<select disabled><option>Psicólogo — código fiscal 255</option></select></label><div class="full actions"><button type="submit">Salvar profissional</button><a class="btn alt" href="/professionals">Cancelar</a></div></form>`;msg,b:=message(r);io.WriteString(w,page("Adicionar profissional",body,msg,b))}
func professionalsOptions(ps []Professional,selected int64)string{var b strings.Builder;b.WriteString(`<option value="">Selecione o profissional</option>`);for _,p:=range ps{sel:="";if p.ID==selected{sel=" selected"};b.WriteString(fmt.Sprintf(`<option value="%d"%s>%s — %s</option>`,p.ID,sel,esc(p.Name),esc(formatCPF(p.CPF))))};return b.String()}
func token()string{b:=make([]byte,18);_,_=rand.Read(b);return hex.EncodeToString(b)}
func (a *App) importPage(w http.ResponseWriter,r *http.Request){ps,e:=a.store.Professionals();if e!=nil{http.Error(w,e.Error(),500);return};if r.Method==http.MethodPost{action:=r.FormValue("action");if action=="preview"{if e:=r.ParseMultipartForm(32<<20);e!=nil{redirectMsg(w,r,"/import","Falha ao ler formulário: "+e.Error(),true);return};f,h,e:=r.FormFile("spreadsheet");if e!=nil{redirectMsg(w,r,"/import","Selecione uma planilha .xlsx.",true);return};defer f.Close();raw,e:=io.ReadAll(io.LimitReader(f,32<<20));if e!=nil{redirectMsg(w,r,"/import",e.Error(),true);return};p,e:=previewXLSX(raw);if e!=nil{redirectMsg(w,r,"/import",e.Error(),true);return};t:=token();a.mu.Lock();a.previews[t]=PreviewBundle{P:p,Source:h.Filename};a.mu.Unlock();a.renderPreview(w,r,ps,t,p,h.Filename);return};if action=="confirm"{pid:=intForm(r,"professional_id");t:=r.FormValue("preview_token");if pid<=0{redirectMsg(w,r,"/import","Selecione explicitamente o profissional antes de importar.",true);return};a.mu.Lock();pb,ok:=a.previews[t];if ok{delete(a.previews,t)};a.mu.Unlock();if !ok{redirectMsg(w,r,"/import","A prévia expirou. Gere novamente.",true);return};c,restr,dup,e:=a.store.Import(pid,pb.Source,pb.P);if e!=nil{redirectMsg(w,r,"/import",e.Error(),true);return};msg:=fmt.Sprintf("Importação concluída: %d lançamentos; %d pendências; %d sem atendimento; %d duplicados ignorados.",c,restr,len(pb.P.Skipped),dup);redirectMsg(w,r,"/payments?professional_id="+strconv.FormatInt(pid,10),msg,false);return}}
    body:=`<h1>Importar planilha Excel</h1><section class="panel"><h2>Selecione o arquivo</h2><form method="post" enctype="multipart/form-data" class="formgrid"><input type="hidden" name="action" value="preview"><label class="full">Planilha .xlsx<input type="file" name="spreadsheet" accept=".xlsx" required></label><div class="full"><button type="submit">Gerar prévia</button></div></form><p class="muted">O sistema detecta automaticamente as competências e os blocos mensais da planilha anual. Linhas com data e valor vazios são tratadas como ausência de atendimento e não são importadas.</p></section>`;msg,b:=message(r);io.WriteString(w,page("Importar Excel",body,msg,b))}
func (a *App) renderPreview(w http.ResponseWriter,r *http.Request,ps []Professional,t string,p Preview,source string){var b strings.Builder;b.WriteString(`<h1>Prévia da importação</h1><section class="panel"><p>Origem: <strong>`+esc(source)+`</strong></p><p>Competências: <strong>`+esc(strings.Join(p.Competences,", "))+`</strong></p><div class="grid"><div><div class="metric">`+strconv.Itoa(len(p.Valid))+`</div><div class="ok">Importáveis</div></div><div><div class="metric">`+strconv.Itoa(len(p.Skipped))+`</div><div class="muted">Sem atendimento</div></div><div><div class="metric">`+strconv.Itoa(len(p.Restricted))+`</div><div class="warn">Pendências</div></div></div></section>`);if len(p.Valid)>0{b.WriteString(`<section class="panel"><h2>Registros importáveis</h2><table><thead><tr><th>Linha</th><th>Competência</th><th>Pagador</th><th>CPF</th><th>Pagamento</th><th>Valor</th></tr></thead><tbody>`);limit:=len(p.Valid);if limit>120{limit=120};for _,x:=range p.Valid[:limit]{b.WriteString(fmt.Sprintf(`<tr><td>%d</td><td>%02d/%04d</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>`,x.SourceRow,x.CompetenceMonth,x.CompetenceYear,esc(x.PayerName),esc(formatCPF(x.PayerCPF)),esc(x.PaymentDate),brMoney(x.AmountCents)))};b.WriteString(`</tbody></table></section>`)};if len(p.Restricted)>0{b.WriteString(`<section class="panel"><h2>Pendências preservadas</h2><p class="muted">Há movimento informado, mas o dado precisa ser corrigido antes de entrar na escrituração.</p><table><thead><tr><th>Linha</th><th>Nome</th><th>CPF informado</th><th>Motivo</th></tr></thead><tbody>`);for _,x:=range p.Restricted{b.WriteString(fmt.Sprintf(`<tr><td>%d</td><td>%s</td><td>%s</td><td class="warn">%s</td></tr>`,x.SourceRow,esc(x.PayerName),esc(x.PayerCPFRaw),esc(x.Reason)))};b.WriteString(`</tbody></table></section>`)};b.WriteString(`<form method="post" class="panel formgrid"><input type="hidden" name="action" value="confirm"><input type="hidden" name="preview_token" value="`+esc(t)+`"><label class="full">Profissional de destino<select name="professional_id" required>`+professionalsOptions(ps,0)+`</select></label><div class="full actions"><button type="submit">Confirmar importação</button><a class="btn alt" href="/import">Cancelar</a></div></form>`);io.WriteString(w,page("Prévia",b.String(),"",false))}
func (a *App) payments(w http.ResponseWriter,r *http.Request){pid,_:=strconv.ParseInt(r.URL.Query().Get("professional_id"),10,64);ps,_:=a.store.Professionals();items,e:=a.store.Payments(pid);if e!=nil{http.Error(w,e.Error(),500);return};var b strings.Builder;b.WriteString(`<h1>Lançamentos</h1><section class="panel"><form method="get" class="formgrid"><label>Profissional<select name="professional_id">`+professionalsOptions(ps,pid)+`</select></label><div style="align-self:end"><button>Filtrar</button></div></form></section><section class="panel"><table><thead><tr><th>Data</th><th>Profissional</th><th>Pagador</th><th>CPF</th><th>Valor</th><th>Status</th></tr></thead><tbody>`);for _,x:=range items{b.WriteString(`<tr><td>`+esc(x.PaymentDate)+`</td><td>`+esc(x.ProfessionalName)+`</td><td>`+esc(x.PayerName)+`</td><td>`+esc(formatCPF(x.PayerCPF))+`</td><td>`+brMoney(x.AmountCents)+`</td><td><span class="tag">`+esc(x.Status)+`</span></td></tr>`)};b.WriteString(`</tbody></table></section>`);if pid>0{b.WriteString(`<section class="panel"><h2>Validar competência para Receita Saúde</h2><form method="post" action="/validate" class="formgrid"><input type="hidden" name="professional_id" value="`+strconv.FormatInt(pid,10)+`"><label>Mês<input name="month" type="number" min="1" max="12" required></label><label>Ano<input name="year" type="number" min="2000" max="2100" value="2026" required></label><div class="full"><button type="submit">Validar lançamentos pendentes</button></div></form></section>`)};msg,bad:=message(r);io.WriteString(w,page("Lançamentos",b.String(),msg,bad))}
func (a *App) validate(w http.ResponseWriter,r *http.Request){if r.Method!=http.MethodPost{http.Redirect(w,r,"/payments",303);return};pid:=intForm(r,"professional_id");m,_:=strconv.Atoi(r.FormValue("month"));y,_:=strconv.Atoi(r.FormValue("year"));n,e:=a.store.Validate(pid,m,y);if e!=nil{redirectMsg(w,r,"/payments?professional_id="+strconv.FormatInt(pid,10),e.Error(),true);return};redirectMsg(w,r,"/payments?professional_id="+strconv.FormatInt(pid,10),fmt.Sprintf("%d lançamento(s) validados para exportação.",n),false)}
func (a *App) export(w http.ResponseWriter,r *http.Request){ps,_:=a.store.Professionals();if r.Method==http.MethodPost{pid:=intForm(r,"professional_id");m,_:=strconv.Atoi(r.FormValue("month"));y,_:=strconv.Atoi(r.FormValue("year"));csv,n,total,e:=a.store.Export(pid,m,y);if e!=nil{redirectMsg(w,r,"/export",e.Error(),true);return};name:=fmt.Sprintf("receita-saude-%04d-%02d-profissional-%d.csv",y,m,pid);w.Header().Set("Content-Type","text/csv; charset=utf-8");w.Header().Set("Content-Disposition",`attachment; filename="`+name+`"`);w.Header().Set("X-GD-Rows",strconv.Itoa(n));w.Header().Set("X-GD-Total-Cents",strconv.FormatInt(total,10));io.WriteString(w,csv);return};body:=`<h1>Exportar escrituração</h1><form method="post" class="panel formgrid"><label class="full">Profissional<select name="professional_id" required>`+professionalsOptions(ps,0)+`</select></label><label>Mês<input name="month" type="number" min="1" max="12" required></label><label>Ano<input name="year" type="number" min="2000" max="2100" value="2026" required></label><div class="full"><button class="gold" type="submit">Gerar CSV Receita Saúde</button></div><p class="muted full">Exporta somente lançamentos validados do profissional e competência selecionados. Formato: ponto e vírgula, sem cabeçalho, 16 campos.</p></form>`;msg,b:=message(r);io.WriteString(w,page("Exportar",body,msg,b))}
func (a *App) restrictions(w http.ResponseWriter,r *http.Request){items,e:=a.store.Restrictions();if e!=nil{http.Error(w,e.Error(),500);return};var b strings.Builder;b.WriteString(`<h1>Pendências de importação</h1>`);if len(items)==0{b.WriteString(`<section class="panel"><p class="ok">Nenhuma pendência.</p></section>`)};for _,x:=range items{b.WriteString(fmt.Sprintf(`<form method="post" action="/restrictions/resolve" class="panel formgrid"><input type="hidden" name="id" value="%d"><div class="full"><strong>%s</strong> · %02d/%04d · linha %d<br><span class="warn">%s</span></div><label>Nome do pagador<input name="payer_name" value="%s" required></label><label>CPF do pagador<input name="payer_cpf" value="%s" required></label><label class="full"><input style="width:auto" type="checkbox" name="same" checked> Pagador e beneficiário são a mesma pessoa</label><label>Nome do beneficiário<input name="beneficiary_name" value="%s"></label><label>CPF do beneficiário<input name="beneficiary_cpf" value="%s"></label><label>Data do pagamento<input name="payment_date" value="%s" placeholder="DD/MM/AAAA" required></label><label>Valor<input name="amount" value="%s" required></label><div class="full"><button type="submit">Corrigir e criar lançamento</button></div></form>`,x.ID,esc(x.ProfessionalName),x.Month,x.Year,x.Row,esc(x.Reason),esc(x.PayerName),esc(x.PayerCPFRaw),esc(x.BeneficiaryName),esc(x.BeneficiaryCPFRaw),esc(x.PaymentDateRaw),esc(x.AmountRaw)))};msg,bad:=message(r);io.WriteString(w,page("Pendências",b.String(),msg,bad))}
func (a *App) resolveRestriction(w http.ResponseWriter,r *http.Request){if r.Method!=http.MethodPost{http.Redirect(w,r,"/restrictions",303);return};id:=intForm(r,"id");e:=a.store.ResolveRestriction(id,r.FormValue("payer_name"),r.FormValue("payer_cpf"),r.FormValue("beneficiary_name"),r.FormValue("beneficiary_cpf"),r.FormValue("payment_date"),r.FormValue("amount"),r.FormValue("same")!="");if e!=nil{redirectMsg(w,r,"/restrictions",e.Error(),true);return};redirectMsg(w,r,"/restrictions","Pendência corrigida. O lançamento foi criado como PENDENTE_REVISAO.",false)}
func (a *App) exit(w http.ResponseWriter,r *http.Request){io.WriteString(w,page("Sair",`<section class="panel"><h1>GD Fiscal Saúde encerrado</h1><p>Esta janela pode ser fechada.</p></section>`,"",false));go func(){time.Sleep(500*time.Millisecond);a.store.Close();os.Exit(0)}()}

func runWeb()error{s,e:=openStore();if e!=nil{return e};app:=&App{store:s,previews:map[string]PreviewBundle{}};ln,e:=net.Listen("tcp","127.0.0.1:0");if e!=nil{s.Close();return e};port:=ln.Addr().(*net.TCPAddr).Port;runtimeDir:=filepath.Join(dataRoot(),"runtime");_ = os.MkdirAll(runtimeDir,0700);_ = os.WriteFile(filepath.Join(runtimeDir,"port.txt"),[]byte(strconv.Itoa(port)),0600);srv:=&http.Server{Handler:app.routes(),ReadHeaderTimeout:10*time.Second};app.server=srv;url:=fmt.Sprintf("http://127.0.0.1:%d/",port);if os.Getenv("GD_FISCAL_NO_BROWSER")!="1"{_ = exec.Command("rundll32","url.dll,FileProtocolHandler",url).Start()};e=srv.Serve(ln);if e!=nil&&e!=http.ErrServerClosed{return e};return nil}
